version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Hong_Kong'
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - chore
    groups:
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - 'eslint'
          - 'prettier'
          - 'vitest'
          - 'jsdom'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(devDeps)'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']